name: Deploy to EC2

on:
  push:
    branches: ["main"] # This triggers the workflow on push to the main branch

jobs:
  test: # New job for running tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout code
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt  # Replace with your command to install dependencies
      - name: Create .env file dynamically
        run: |
          echo "ENV=${ENV}" >> env
          echo "EC2_USERNAME=${EC2_USERNAME}" >> env
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> env
      - name: Run tests with pytest # run tests with pytest
        run: |
          python -m pytest tests/test_app.py

  deploy: # Existing deploy job (modified)
    runs-on: ubuntu-latest
    needs: test # This job needs the 'test' job to succeed before running
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Set up SSH key and whitelist EC2 IP address
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${EC2_HOST} >> ~/.ssh/known_hosts

      - name: Create .env file dynamically
        env:
          ENV: ${{ secrets.ENV }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          OPENAI_API_KEY: ${{ secrets.EC2_API_KEY }} # Replace with your secrets
        run: |
          echo "ENV=${ENV}" >> env
          echo "EC2_USERNAME=${EC2_USERNAME}" >> env
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> env

      - name: Copy files to remote server
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          scp -r * $EC2_USERNAME@$EC2_HOST:/home/ubuntu/

      - name: Run Bash Script To Delpoy App
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "chmod +x ./deploy.sh && ./deploy.sh"
